spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Karthi@123
    url: jdbc:mysql://localhost:3306/BookData
    username: root
   

    mvc:
      pathmatch:
            matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
