spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Karthi@123
    url: jdbc:mysql://localhost:3306/AssociationMapping
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
